import { defineConfig } from "tsup";

export default defineConfig({
  bundle: false,
  clean: true,
  dts: true,
  entry: [
    "src/index.ts",
    "src/program-v1.ts",
    "src/kalada-v1/canonicalize.ts",
    "src/kalada-v1/canonical-input.ts",
    "src/kalada-v1/codec.ts",
    "src/kalada-v1/compile.ts",
    "src/kalada-v1/dependencies.ts",
    "src/kalada-v1/diagnostics.ts",
    "src/kalada-v1/evaluate.ts",
    "src/kalada-v1/evaluation-delivery.ts",
    "src/kalada-v1/evaluation-frames.ts",
    "src/kalada-v1/evaluation-machine.ts",
    "src/kalada-v1/evaluation-resolution.ts",
    "src/kalada-v1/evaluation-state.ts",
    "src/kalada-v1/factories.ts",
    "src/kalada-v1/function-contracts.ts",
    "src/kalada-v1/index.ts",
    "src/kalada-v1/json.ts",
    "src/kalada-v1/limits.ts",
    "src/kalada-v1/runtime-values.ts",
    "src/kalada-v1/schemas.ts",
    "src/kalada-v1/static-analysis.ts",
    "src/kalada-v1/static-types.ts",
    "src/kalada-v1/temporal.ts",
    "src/kalada-v1/temporal-evaluation.ts",
    "src/kalada-v1/types.ts",
    "src/kalada-v1/values.ts",
    "src/kuery-v1/callback-promise.ts",
    "src/kuery-v1/canonicalize.ts",
    "src/kuery-v1/compile.ts",
    "src/kuery-v1/dependencies.ts",
    "src/kuery-v1/evaluate.ts",
    "src/kuery-v1/index.ts",
    "src/kuery-v1/inspect.ts",
    "src/kuery-v1/json-schema.ts",
    "src/kuery-v1/limits.ts",
    "src/kuery-v1/profile.ts",
    "src/kuery-v1/result.ts",
    "src/kuery-v1/standard-profile.ts",
    "src/kuery-v1/types.ts",
  ],
  format: ["esm", "cjs"],
  outExtension({ format }) {
    return { js: format === "cjs" ? ".cjs" : ".js" };
  },
  sourcemap: true,
  target: "node22",
  treeshake: true,
});
