export type {
  AnalysisCheckpoint,
  AnalysisOutcome,
  AnalysisResult,
  CancellationToken,
  CancelledResult,
  CandidatePresence,
  CandidateSupport,
  CompletionItem,
  CompletionOutcome,
  CompletionResult,
  DiagnosticsOutcome,
  DiagnosticsResult,
  DocumentIdentity,
  DocumentOpen,
  DocumentSnapshot,
  DocumentUpdate,
  EnvironmentSnapshot,
  EnvironmentUpdate,
  FormatCheckpoint,
  FormatOutcome,
  FormatResult,
  HoverInfo,
  HoverOutcome,
  HoverResult,
  LanguageAnalysis,
  LanguageService,
  LanguageServiceCheckpoint,
  LanguageServiceDiagnostic,
  LanguageServiceErrorCode,
  LanguageServiceOperation,
  RequestOptions,
  ResultStatus,
  ShapeSummary,
  ShapeSummaryField,
  SnapshotIdentity,
  TextEdit,
  ToolingCheckpoint,
  ToolingEvidence,
  ToolingEvidenceCode,
  Utf16LineIndex,
  WorkspaceSnapshot,
} from "./contracts.js";
export { LanguageServiceError } from "./errors.js";
export {
  createExpressionsDiagnosticProvider,
  type ExpressionsDiagnostic,
  type ExpressionsDiagnosticProvider,
  type ExpressionsDocument,
  type ExpressionsEnvironment,
  type ExpressionsEnvironmentResolver,
} from "./expressions-provider.js";
export { createUtf16LineIndex } from "./line-index.js";
export { createLanguageService } from "./service.js";
